---
packages:
  additional_packages:
    - id: "element-desktop"
      name: "Element"
      description: "Matrix-based end-to-end encrypted messenger and secure collaboration app."
      snap: true
    - id: "thunderbird"
      name: "Thunderbird"
      description: "Email, newsfeed, chat, and calendaring client."
      snap: true
    - id: "virt-manager"
      name: "Virtual Machine Manager"
      description: "Desktop user interface for managing virtual machines through libvirt."
      snap: false
    - id: "krita"
      name: "Krita"
      description: "Graphics editor designed primarily for digital art and 2D animation."
      snap: true
  minimal_remove_packages:
    - snapd aisleriot
    - atril
    - cheese
    - simple-scan
    - gdebi
    - gparted
    - "*kvantum*"
    - "libreoffice*"
    - gnome-mahjongg
    - gnome-mines
    - remmina
    - rhythmbox
    - shotwell
    - gnome-sudoku
    - synaptic
    - transmission-gtk
    - vlc
    - stacer
  installer_remove_packages:
    - "^live-*"
    - calamares-settings-ubuntu-unity
    - calamares
    - cifs-utils
  regular_install_packages:
    - language-pack-$LOCALE
    - language-pack-gnome-$LOCALE
    - language-pack-kde-$LOCALE
    - hunspell-$LOCALE
    - libreoffice-help-$LOCALE
    - libreoffice-l10n-$LOCALE
  refresh_snaps:
    - "firefox"
